name: GitHub Action Practice

on:
  push:
    branches: [master]

jobs:
  run-npm-on-ubuntu-22:
    name: Run npm on Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm help
